SELECT
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') as 'REVIEW_DATE'
FROM MEMBER_PROFILE A
INNER JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (
    SELECT A.MEMBER_ID
    FROM MEMBER_PROFILE A
    INNER JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY A.MEMBER_ID
    ORDER BY COUNT(1) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE ASC;